kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: susi-gitterbot
  namespace: gitterbot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: susi-gitterbot
    spec:
      containers:
      - name: susi-gitterbot
        image: fossasia/susi_gitterbot:latest
        env:
        - name: ROOM_ID
          value: "59345f93d73408ce4f64a22d"
        - name: TOKEN
          value: "b16b378c0f68bc92c7ea980e0dbbc9e616dfc7a9"
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: susi-gitterbot
      restartPolicy: Always
