kind: Service
apiVersion: v1
metadata:
  name: susi-gitterbot
  namespace: gitterbot
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: susi-gitterbot
  type: LoadBalancer