kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: susi-gitterbot1
  namespace: gitterbot1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: susi-gitterbot1
    spec:
      containers:
      - name: susi-gitterbot1
        image: aliayubkhan/susi_gitterbot1:latest
        env:
        - name: ROOM_ID
          value: "59a695bcd73408ce4f739399"
        - name: TOKEN
          value: "db187b9812d0c977966a0919e90ce3d3724f532e"
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: susi-gitterbot1
      restartPolicy: Always
