kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: susi-gitterbot
  namespace: gitterbot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: susi-gitterbot
    spec:
      containers:
      - name: susi-gitterbot
        image: fossasia/susi_gitterbot:0483cb76527bdcba8dfec2cad19fb2c4ff513929
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: susi-gitterbot
      restartPolicy: Always
